[project]
name = "wurl"
version = "0.1.2"
description = "wurl is a command-line HTTP client for making requests, it comes with Rich syntax highlighting and formatting."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Kartik-2239" }
]
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "rich>=15.0.0",
    "yattag>=1.16.1",
]

[project.scripts]
wurl = "wurl.main:main"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
